theme: jekyll-theme-minimal
lsi: false
safe: true
source: docs
url: "https://biocomputing-teaching.github.io"
baseurl: "/Curso-MD-Analisis"
permalink: pretty
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
incremental: false
layouts_dir: _layouts
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
